[server]
enableStaticServing = true

[[theme.fontFaces]]
family = "Better Minds"
url = "static/fonts/BetterMinds-PKJnB.ttf"
style = "normal"
weight = 600

[theme]
font = "Better Minds"
fontSize = 30